name: PR
on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  # デリバリー（ビルド&デプロイ)
  delivery:
    uses: nw-union/.github/.github/workflows/deploy_workers_with_bun.yml@main
    secrets: inherit
    with:
      command: versions upload --message "Deployed by GitHub Actions (${{ github.ref_name }})"

  # コードの静的解析
  analysis:
    uses: nw-union/.github/.github/workflows/code_analysis.yml@main
    secrets: inherit

  # PR の設定確認
  chores:
    uses: nw-union/.github/.github/workflows/pr_chores.yml@main
    secrets: inherit

